version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
    post_create_environment:
      # TODO: Allow latest version of poetry install
      # Poetry >=v1.8.0 breaks the docs build. Pin poetry install to v.1.7.1 to allow docs to work
      - pip install poetry==1.7.1
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install docs dependencies.
      - poetry install --only docs

sphinx:
  configuration: docs/src/conf.py
