FROM python:3.11-slim

RUN apt-get update && apt-get install -y gettext-base

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

ENV DAGSTER_HOME=/opt/dagster/ska-src-maltopuft-etl
WORKDIR $DAGSTER_HOME

COPY workspace.yaml .
COPY dagster.yaml dagster.template.yaml