FROM python:3.11-slim

# Install these in core
# Install poetry and dagster deps
RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker

ENV DAGSTER_HOME=/opt/dagster/ska-src-maltopuft-etl

WORKDIR $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME